package com.example.lostandfound.model;

public class Collection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Collection.coId
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    private String coid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Collection.itemId
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    private String itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Collection.userId
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Collection.coId
     *
     * @return the value of Collection.coId
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    public String getCoid() {
        return coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Collection.coId
     *
     * @param coid the value for Collection.coId
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    public void setCoid(String coid) {
        this.coid = coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Collection.itemId
     *
     * @return the value of Collection.itemId
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Collection.itemId
     *
     * @param itemid the value for Collection.itemId
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    public void setItemid(String itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Collection.userId
     *
     * @return the value of Collection.userId
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Collection.userId
     *
     * @param userid the value for Collection.userId
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }
}