package com.example.lostandfound.model;

public class Collection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Collection.coId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer coid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Collection.itemId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Collection.userId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Collection.coId
     *
     * @return the value of Collection.coId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getCoid() {
        return coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Collection.coId
     *
     * @param coid the value for Collection.coId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setCoid(Integer coid) {
        this.coid = coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Collection.itemId
     *
     * @return the value of Collection.itemId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Collection.itemId
     *
     * @param itemid the value for Collection.itemId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Collection.userId
     *
     * @return the value of Collection.userId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Collection.userId
     *
     * @param userid the value for Collection.userId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}