package com.example.lostandfound.model;

import java.util.Date;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.itemId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.itemType
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer itemtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.category
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.title
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.place
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String place;
    private String datetime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.longitude
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.latitude
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.createDatetime
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Date createdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.content
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.createUserId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.flag
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.itemId
     *
     * @return the value of Item.itemId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.itemId
     *
     * @param itemid the value for Item.itemId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.itemType
     *
     * @return the value of Item.itemType
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getItemtype() {
        return itemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.itemType
     *
     * @param itemtype the value for Item.itemType
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setItemtype(Integer itemtype) {
        this.itemtype = itemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.category
     *
     * @return the value of Item.category
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.category
     *
     * @param category the value for Item.category
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.title
     *
     * @return the value of Item.title
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.title
     *
     * @param title the value for Item.title
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.place
     *
     * @return the value of Item.place
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getPlace() {
        return place;
    }
    public String getDatetime(){return datetime; }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.place
     *
     * @param place the value for Item.place
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setPlace(String place) {
        this.place = place;
    }
    public void setDatetime(String datetime){this.datetime=datetime;}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.longitude
     *
     * @return the value of Item.longitude
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.longitude
     *
     * @param longitude the value for Item.longitude
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.latitude
     *
     * @return the value of Item.latitude
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.latitude
     *
     * @param latitude the value for Item.latitude
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.createDatetime
     *
     * @return the value of Item.createDatetime
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.createDatetime
     *
     * @param createdatetime the value for Item.createDatetime
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.content
     *
     * @return the value of Item.content
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.content
     *
     * @param content the value for Item.content
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.createUserId
     *
     * @return the value of Item.createUserId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.createUserId
     *
     * @param createuserid the value for Item.createUserId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.flag
     *
     * @return the value of Item.flag
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.flag
     *
     * @param flag the value for Item.flag
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}