package com.example.lostandfound.model;

public class Picture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Picture.picId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer picid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Picture.itemId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Picture.picUrl
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String picurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Picture.picId
     *
     * @return the value of Picture.picId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getPicid() {
        return picid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Picture.picId
     *
     * @param picid the value for Picture.picId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setPicid(Integer picid) {
        this.picid = picid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Picture.itemId
     *
     * @return the value of Picture.itemId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Picture.itemId
     *
     * @param itemid the value for Picture.itemId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Picture.picUrl
     *
     * @return the value of Picture.picUrl
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Picture.picUrl
     *
     * @param picurl the value for Picture.picUrl
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }
}