package com.example.lostandfound.model;

public class UserTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserTable.userId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserTable.username
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserTable.usrpwd
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String usrpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserTable.phoneNumber
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserTable.credit
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserTable.score
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserTable.portrait
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    private String portrait;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserTable.userId
     *
     * @return the value of UserTable.userId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserTable.userId
     *
     * @param userid the value for UserTable.userId
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserTable.username
     *
     * @return the value of UserTable.username
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserTable.username
     *
     * @param username the value for UserTable.username
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserTable.usrpwd
     *
     * @return the value of UserTable.usrpwd
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getUsrpwd() {
        return usrpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserTable.usrpwd
     *
     * @param usrpwd the value for UserTable.usrpwd
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setUsrpwd(String usrpwd) {
        this.usrpwd = usrpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserTable.phoneNumber
     *
     * @return the value of UserTable.phoneNumber
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserTable.phoneNumber
     *
     * @param phonenumber the value for UserTable.phoneNumber
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserTable.credit
     *
     * @return the value of UserTable.credit
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserTable.credit
     *
     * @param credit the value for UserTable.credit
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserTable.score
     *
     * @return the value of UserTable.score
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserTable.score
     *
     * @param score the value for UserTable.score
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserTable.portrait
     *
     * @return the value of UserTable.portrait
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserTable.portrait
     *
     * @param portrait the value for UserTable.portrait
     *
     * @mbg.generated Wed May 22 17:34:48 CST 2019
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }
}