package com.example.lostandfound.mapper;

import com.example.lostandfound.model.Collection;

public interface CollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Collection
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int deleteByPrimaryKey(String coid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Collection
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int insert(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Collection
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int insertSelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Collection
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    Collection selectByPrimaryKey(String coid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Collection
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int updateByPrimaryKeySelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Collection
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int updateByPrimaryKey(Collection record);
}