package com.example.lostandfound.mapper;

import com.example.lostandfound.model.Item;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Item
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int deleteByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Item
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Item
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Item
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    Item selectByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Item
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Item
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int updateByPrimaryKey(Item record);
}