package com.example.lostandfound.mapper;

import com.example.lostandfound.model.Message;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int deleteByPrimaryKey(String msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    Message selectByPrimaryKey(String msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message
     *
     * @mbg.generated Tue May 14 20:23:06 CST 2019
     */
    int updateByPrimaryKey(Message record);
}